ansible_managed_banner: '## This file is managed by Ansible ##'
global_dns_domain: duke.lan
external_dns_domain: m-duke.nl
global_default_gateway: 192.168.1.1
global_primary_nameserver: 192.168.1.53
external_ip_address__enc: ENC[AES256_GCM,data:ZXOQfKj1BV100R9vhCY=,iv:JJdRcJ95hrVUiAZ9YBPm0jRWxD8rygCwAkWsJU0ySpg=,tag:z1kZCKl0bP2sp7iSgZB7gg==,type:str]
bind__tsig_key__enc: ENC[AES256_GCM,data:LSk3UaKgAeIlKPdL7wccQjT2rspvXJ4kf4jmdVa1v5Nvggmc6Clmo0+9L3g=,iv:8ksAIMPLcjVPSMJUtngdcID4nq1UvK8lkVxiH2xtnAE=,tag:+/MmlzlCVTH5kmWph+uiIw==,type:str]
default_geo_location_lat: "51.7997426198218"
default_geo_location_lon: "4.48049039126418"
packages__default_packages:
    - vim
    - chrony
    - curl
    - gnupg
proxmox_lxc_containers__root_password__enc: ENC[AES256_GCM,data:37xxbrqXK3LQ,iv:Mxry/zEVX7bIDHmk1SAhVz+mORU8M81xTrRtcDKayg4=,tag:vKv4ARk3+qbbdQIP91A+bA==,type:str]
zabbix__debian_repo_download_url: https://repo.zabbix.com/zabbix/7.2/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.2+ubuntu24.04_all.deb
zabbix__debian_repo_download_file: /opt/zabbix-release_latest_7.2+ubuntu24.04_all.deb
# TODO: fix the dns server, should be zabbix.duke.lan
zabbix__server_hostname: 192.168.1.51
zabbix__api_token__enc: ENC[AES256_GCM,data:s3qWCZTy+NXg9T9XH5P/zAyMw9eHqH4HSo8ceI2ublz3bUbnU8VxxspTNLi6YXpmyYVqqEoUR6rJBUFxsG3q7g==,iv:KCCWi88dpEN8VlcwyXQ86vavxMtkNLFsvv0vXrKfyxw=,tag:DdBhG0NyCbyk/DxKmAudYA==,type:str]
alloy__group_access:
    - zabbix
sops:
    age:
        - recipient: age129fjlypxle3gxtj4z77hp7f33cvh5yluymzn5tyfgr2hrc6f8dhq43e765
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTDROTnc0UGpncTdtdlll
            a1l5RHozbzhhaVlEeE8yUWVkTEsvWUoyRUFrClN5QWxMVG1QdzhWdGdGaTVjWUN5
            ZnRPNmRmbzRkcGRSVUF0UGxxbEhqRVUKLS0tICtUeXJ1aUxvcEY1Y1hDU2FVajRX
            aGJScE82R3M5d3Rpem5OYTgza1dMZ3cK0B2nuVlisF0SOWVp95q6mArPl1mNyr4R
            3rY3O99P7KM7FFz0GdjuH3vVBlOeQTfIF7BpDgh8+NnsYxU26awPMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T07:42:27Z"
    mac: ENC[AES256_GCM,data:WWNLNWf9xCVDIbltlZ+pv4onwT0oRTAifPBoTybRdoLhwAhNStbd7xKK91fYPNxL6vqSoa1MF4BkmkKBsLEV2HopOKjtbShib2YdFvVO8gfXRlBLqO+c8AiVMUER7KSeMLHsWFPWA015DnsMU/ooLTKOO+0Zq4mcPrgO7wCzwd0=,iv:iKjwh9tipY5Wg/5B5O/RJSmfkAXU618R1KtmN8V0ynU=,tag:xJOhig3EvkfqqRvXNwd7IA==,type:str]
    encrypted_suffix: __enc
    version: 3.11.0
