docker__prune: true
zabbix__template_id:
    # Linux by Zabbix agent
    - "10001"
    # Docker by Zabbix agent 2
    - "10318"
elastic__password__enc: elastic_Pa$$w0rd!
nginx_proxy_manager__password__enc: proxy_Pa$$w0rd!
my_email_account__enc: michael_duke@outlook.com
gitea__mysql_db_name__enc: gitea
gitea__mysql_user_name__enc: gitea
gitea__mysql_user_password__enc: gitea_Pa$$w0rd!
gitea__mysql_root_password__enc: Pa$$w0rd!
ddclient__username__enc: michael_duke@outlook.com
ddclient__password__enc: Oros-4-life!
ddclient__hostname__enc: sirdukey.mywire.org
alloy__group_access:
    - docker
    - zabbix
packages__custom_packages:
    - nfs-common
nfs__server: "'192.168.1.62'"