docker__prune: true
zabbix__template_id:
    # Linux by Zabbix agent
    - "10001"
    # Docker by Zabbix agent 2
    - "10318"
elastic__password__enc: ENC[AES256_GCM,data:d5TbP0sbAO7re0HBGQrTnXs=,iv:FBZRse2K2CL5ppJeAuD01Hfwaub4ImiSGaiV2U1+kbQ=,tag:34pbbIadWrZxI9zKQNHggA==,type:str]
nginx_proxy_manager__password__enc: ENC[AES256_GCM,data:TzSo/l+M4rqFIGse/PLI,iv:+9nenFYPTbBMkifHILc2QVqTZrooYnnZ7ufMBTq2teg=,tag:7fyi1KfuOYxFbLR/X2Xm3w==,type:str]
my_email_account__enc: ENC[AES256_GCM,data:1SJSh7aFyi5YZnK/Gc2foFpUoe2pNGwM,iv:MiBRfqEZ9v2DsfHcB02gfwGU05KWoMTY5FlqP/WQjVA=,tag:oGwU+jIuDsHDJcv9qpMS5w==,type:str]
gitea__mysql_db_name__enc: ENC[AES256_GCM,data:s1HhGUs=,iv:BuQFp75ZjhUpuyVq0gFFlHYGyfWpSib0PUcoDOLsaHI=,tag:ozdq26jpPr2rxQGaPJhGMA==,type:str]
gitea__mysql_user_name__enc: ENC[AES256_GCM,data:CiTkdA8=,iv:Dn1PbiOC7g8wi+HWCCBP4KyetzppWf5VgqYEZ21zthU=,tag:ijreNvnsGRj27OrAFEXWeg==,type:str]
gitea__mysql_user_password__enc: ENC[AES256_GCM,data:REq59Y/y7/ca7ID7G8Zi,iv:/cBAZxy7rFtVP9b9YN1MHIUNw+vwMxGbd5OQydYAUsg=,tag:9LEHrZrzZzSATmvU8cPsrw==,type:str]
gitea__mysql_root_password__enc: ENC[AES256_GCM,data:E6TqaHu/k8ls,iv:CXk88hOnjZfFEUoJfGa5xW0FVIR/6u27VcTMYLA5dsM=,tag:Pv39hVTqCqILwjQRl793ug==,type:str]
ddclient__username__enc: ENC[AES256_GCM,data:EqxqT1yx13AFOwraNzkchq5gXTdOnRDY,iv:RRPSTTyO3u7zNl8YQ1ft3z4rJoCHnHQL5iL3Sg4ODFs=,tag:V6/KkNhViJSj9vuCt3O4AA==,type:str]
ddclient__password__enc: ENC[AES256_GCM,data:sjJTROMeGases7pN,iv:XUdKpy+NUT8QB7mY1HP1s7TiDs/IdNZI0OcR7O4PEOw=,tag:bCwhfOC/WtIrSXVcBANkVw==,type:str]
ddclient__hostname__enc: ENC[AES256_GCM,data:eUfrLY7rG85mH/5jSw8YArfJVA==,iv:Rrz049Vv6SN3pYQNqOa0bob/N7hdnkJBGTrjtCa3NX8=,tag:Yjd9D9ca8Ry3aoWCV1c+8w==,type:str]
alloy__group_access:
    - docker
    - zabbix
packages__custom_packages:
    - nfs-common
nfs__server: 192.168.1.62
sops:
    age:
        - recipient: age129fjlypxle3gxtj4z77hp7f33cvh5yluymzn5tyfgr2hrc6f8dhq43e765
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoLzd1cFNKaE03VUFDSm5C
            Y1dxNS9iZTdadU1jYjVZTXorQWVhUmwrRlNBCmFCT3d1Qk9UcVB3NEI1b0Z6Vnpw
            QXNWSzVZMzRnYTlOK2tvN0lpQzJPekEKLS0tIE5JL2tkRC82UDg0VEVSTFZyNXRp
            cEpXbTUzajl3MzB5VWF1SFFGeS9EcGcKT5IfUJWZTu7u7wUMtgndHOziOcZ8A7LA
            IBWHwIcrXlS5/LCtLWc1SVF0cU65e/IoTN+4xlQNxxkG9rvykrx0kA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T21:06:16Z"
    mac: ENC[AES256_GCM,data:+qbjallwVKXnCT5xn24MP/5kEgHMtCy9V4kneyP2nawT5Csp1bD1kYPzIKphAlWb3ZQc3iDRA0soglsLKfqrUyceAqW6Zk/azsyPWU4X4NwlloyyLZEdE93UpRwO8WpDPK+u6nww+xSHNhlI6GuL+Ni1FISjMHrpIiJDitEpO1M=,iv:n3E0eDi2y09Tevz2lrdDRfdFNGg422oNzEsxVGsc6pM=,tag:AOFUXnqQkwxb+vHfeZjXTw==,type:str]
    encrypted_suffix: __enc
    version: 3.11.0
