---
- name: CONTAINER | Pull image for Jellyfin
  community.docker.docker_image:
    name: jellyfin/jellyfin
    source: pull
  tags: jellyfin

- name: CONTAINER | Ensure Jellyfin config volume is present
  community.docker.docker_volume:
    name: jellyfin_config
    state: present
  tags: jellyfin

- name: CONTAINER | Ensure Jellyfin cache volume is present
  community.docker.docker_volume:
    name: jellyfin_cache
    state: present
  tags: jellyfin

- name: CONTAINER | Ensure mount point directory exists
  ansible.builtin.file:
    path: /data
    state: directory
    mode: '0755'
  become: true
  tags: jellyfin

- name: CONTAINER | Ensure data is mounted from nfs share, add to fstab if not present
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "{{ nfs__server }}:/data /data nfs defaults,ro 0 0"
    create: true
  become: true
  tags: jellyfin

- name: CONTAINER | Run fstab to mount /data
  ansible.builtin.command: mount -a
  become: true
  tags: jellyfin

- name: CONTAINER | Run Jellyfin container
  community.docker.docker_container:
    name: jellyfin
    state: started
    restart_policy: "always"
    ports:
      - "8096:8096/tcp"
      - "7359:7359/udp"
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - /data:/media:ro
    image: jellyfin/jellyfin
  tags: jellyfin