---
- name: CONTAINER | Pull the latest qbittorrent image
  community.docker.docker_image:
    name: lscr.io/linuxserver/qbittorrent:latest
    source: pull
  tags: qbittorrent

- name: CONTAINER | Ensure media-config is run
  ansible.builtin.include_tasks: media-config.yml
  tags: qbittorrent

- name: Ensure config volume is present
  community.docker.docker_volume:
    name: qbittorrent_config
    state: present
  tags: qbittorrent

- name: CONTAINER | Run qbittorrent container
  community.docker.docker_container:
    name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    state: started
    restart_policy: "unless-stopped"
    ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "8080:8080"
    volumes:
      - qbittorrent_config:/config
      - /data:/data
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: Etc/UTC
    networks:
      - name: media_network
  tags: qbittorrent
