---
- name: CONTAINER | Pull the latest sonarr image
  community.docker.docker_image:
    name: lscr.io/linuxserver/sonarr:latest
    source: pull
  tags: sonarr

- name: CONTAINER | Ensure media-config is run
  ansible.builtin.include_tasks: media-config.yml
  tags: sonarr

- name: CONTAINER | Ensure config volume is present
  community.docker.docker_volume:
    name: sonarr_config
    state: present
  tags: sonarr

- name: CONTAINER | Run sonarr container
  community.docker.docker_container:
    name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    state: started
    restart_policy: "unless-stopped"
    ports:
      - "8989:8989"
    volumes:
      - sonarr_config:/config
      - /data:/data
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: Etc/UTC
    networks:
      - name: media_network
  tags: sonarr
